apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2
spec:
  selector:
    matchLabels:
      app: ms2

  template:
    metadata:
      labels:
        app: ms2

    spec:
      containers:
        - name: ms2

          image: israelborba/ms2
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms2-svc
spec:
  selector:
    app: ms2
  ports:
    - port: 8080
      targetPort: 3000
