apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1
spec:
  selector:
    matchLabels:
      app: ms1

  template:
    metadata:
      labels:
        app: ms1

    spec:
      containers:
        - name: ms1

          image: israelborba/ms1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-svc
spec:
  selector:
    app: ms1
  ports:
    - port: 3000
      targetPort: 3000
