apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms4
spec:
  selector:
    matchLabels:
      app: ms4

  template:
    metadata:
      labels:
        app: ms4

    spec:
      containers:
        - name: ms4

          image: israelborba/ms4
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms4-svc
spec:
  selector:
    app: ms4
  ports:
    - port: 8080
      targetPort: 3000
