apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3
spec:
  selector:
    matchLabels:
      app: ms3

  template:
    metadata:
      labels:
        app: ms3

    spec:
      containers:
        - name: ms3

          image: israelborba/ms3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms3-svc
spec:
  selector:
    app: ms3
  ports:
    - port: 3000
      targetPort: 3000
